// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0--rc2
// source: communications.proto

package gRPC

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Data            string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	HashSelfParent  string                 `protobuf:"bytes,2,opt,name=HashSelfParent,proto3" json:"HashSelfParent,omitempty"`
	HashOtherParent string                 `protobuf:"bytes,3,opt,name=HashOtherParent,proto3" json:"HashOtherParent,omitempty"`
	HashOwn         string                 `protobuf:"bytes,4,opt,name=HashOwn,proto3" json:"HashOwn,omitempty"`
	Timestamp       int64                  `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_communications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_communications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_communications_proto_rawDescGZIP(), []int{0}
}

func (x *NodeRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *NodeRequest) GetHashSelfParent() string {
	if x != nil {
		return x.HashSelfParent
	}
	return ""
}

func (x *NodeRequest) GetHashOtherParent() string {
	if x != nil {
		return x.HashOtherParent
	}
	return ""
}

func (x *NodeRequest) GetHashOwn() string {
	if x != nil {
		return x.HashOwn
	}
	return ""
}

func (x *NodeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type NodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_communications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_communications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_communications_proto_rawDescGZIP(), []int{1}
}

func (x *NodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_communications_proto protoreflect.FileDescriptor

const file_communications_proto_rawDesc = "" +
	"\n" +
	"\x14communications.proto\x12\x04gRPC\"\xab\x01\n" +
	"\vNodeRequest\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\x12&\n" +
	"\x0eHashSelfParent\x18\x02 \x01(\tR\x0eHashSelfParent\x12(\n" +
	"\x0fHashOtherParent\x18\x03 \x01(\tR\x0fHashOtherParent\x12\x18\n" +
	"\aHashOwn\x18\x04 \x01(\tR\aHashOwn\x12\x1c\n" +
	"\tTimestamp\x18\x05 \x01(\x03R\tTimestamp\"(\n" +
	"\fNodeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2C\n" +
	"\fGraphService\x123\n" +
	"\bSendNode\x12\x11.gRPC.NodeRequest\x1a\x12.gRPC.NodeResponse\"\x00B\aZ\x05/gRPCb\x06proto3"

var (
	file_communications_proto_rawDescOnce sync.Once
	file_communications_proto_rawDescData []byte
)

func file_communications_proto_rawDescGZIP() []byte {
	file_communications_proto_rawDescOnce.Do(func() {
		file_communications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_communications_proto_rawDesc), len(file_communications_proto_rawDesc)))
	})
	return file_communications_proto_rawDescData
}

var file_communications_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_communications_proto_goTypes = []any{
	(*NodeRequest)(nil),  // 0: gRPC.NodeRequest
	(*NodeResponse)(nil), // 1: gRPC.NodeResponse
}
var file_communications_proto_depIdxs = []int32{
	0, // 0: gRPC.GraphService.SendNode:input_type -> gRPC.NodeRequest
	1, // 1: gRPC.GraphService.SendNode:output_type -> gRPC.NodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_communications_proto_init() }
func file_communications_proto_init() {
	if File_communications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_communications_proto_rawDesc), len(file_communications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_communications_proto_goTypes,
		DependencyIndexes: file_communications_proto_depIdxs,
		MessageInfos:      file_communications_proto_msgTypes,
	}.Build()
	File_communications_proto = out.File
	file_communications_proto_goTypes = nil
	file_communications_proto_depIdxs = nil
}
